/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ServicesWaterHeatersRouteImport } from './routes/services/water-heaters'
import { Route as ServicesSewerServicesRouteImport } from './routes/services/sewer-services'
import { Route as ServicesPlumbingRouteImport } from './routes/services/plumbing'
import { Route as ServicesDrainCleaningRouteImport } from './routes/services/drain-cleaning'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWaterHeatersRoute = ServicesWaterHeatersRouteImport.update({
  id: '/services/water-heaters',
  path: '/services/water-heaters',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSewerServicesRoute = ServicesSewerServicesRouteImport.update({
  id: '/services/sewer-services',
  path: '/services/sewer-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPlumbingRoute = ServicesPlumbingRouteImport.update({
  id: '/services/plumbing',
  path: '/services/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDrainCleaningRoute = ServicesDrainCleaningRouteImport.update({
  id: '/services/drain-cleaning',
  path: '/services/drain-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/drain-cleaning': typeof ServicesDrainCleaningRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/sewer-services': typeof ServicesSewerServicesRoute
  '/services/water-heaters': typeof ServicesWaterHeatersRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/drain-cleaning': typeof ServicesDrainCleaningRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/sewer-services': typeof ServicesSewerServicesRoute
  '/services/water-heaters': typeof ServicesWaterHeatersRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/drain-cleaning': typeof ServicesDrainCleaningRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/sewer-services': typeof ServicesSewerServicesRoute
  '/services/water-heaters': typeof ServicesWaterHeatersRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/coupons'
    | '/service-area'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/drain-cleaning'
    | '/services/plumbing'
    | '/services/sewer-services'
    | '/services/water-heaters'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/coupons'
    | '/service-area'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/drain-cleaning'
    | '/services/plumbing'
    | '/services/sewer-services'
    | '/services/water-heaters'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/coupons'
    | '/service-area'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/drain-cleaning'
    | '/services/plumbing'
    | '/services/sewer-services'
    | '/services/water-heaters'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CouponsRoute: typeof CouponsRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesDrainCleaningRoute: typeof ServicesDrainCleaningRoute
  ServicesPlumbingRoute: typeof ServicesPlumbingRoute
  ServicesSewerServicesRoute: typeof ServicesSewerServicesRoute
  ServicesWaterHeatersRoute: typeof ServicesWaterHeatersRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/water-heaters': {
      id: '/services/water-heaters'
      path: '/services/water-heaters'
      fullPath: '/services/water-heaters'
      preLoaderRoute: typeof ServicesWaterHeatersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sewer-services': {
      id: '/services/sewer-services'
      path: '/services/sewer-services'
      fullPath: '/services/sewer-services'
      preLoaderRoute: typeof ServicesSewerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/plumbing': {
      id: '/services/plumbing'
      path: '/services/plumbing'
      fullPath: '/services/plumbing'
      preLoaderRoute: typeof ServicesPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/drain-cleaning': {
      id: '/services/drain-cleaning'
      path: '/services/drain-cleaning'
      fullPath: '/services/drain-cleaning'
      preLoaderRoute: typeof ServicesDrainCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CouponsRoute: CouponsRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesDrainCleaningRoute: ServicesDrainCleaningRoute,
  ServicesPlumbingRoute: ServicesPlumbingRoute,
  ServicesSewerServicesRoute: ServicesSewerServicesRoute,
  ServicesWaterHeatersRoute: ServicesWaterHeatersRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
